message:
  enabled: off

  command:
    cooldown: "Shoma baraye &4{duration} sanie &cejazeye zadane in command ro nadarid."

    gamemode: "{paradise_prefix} Gamemode shoma be &d{gamemode}&f taghir yaft."
    inventory_see_self: "Shoma nemitavanid inventory khodeton ro negah konid."

    search:
      item_air: "Shoma chizi dar dastetoon nadarid."
      item_invalid: "Itemi ke entekhab kardid to shop vojod nadare."

    clear_inventory: "{paradise_prefix} Inventory &d{player}&f clear shod."
    fly: "&#00D6FF&lFLIGHT &fFly shoma {state} &fshod."
    heal: "&#D1001C&lHEAL &fShoma heal shodid."
    feed: "&#ffd572&lFEED &fGhazaton por shod."

    milk: "&#44ff8b&lMILK &fTamame potion effect haye shoma hazf shod."
    night_vision: "&#4768ff&lVISION &fEffecte night vision shoma {state} &fshod."
    godmode: "&#8fff56&lGOD &fEffecte god mod shoma {state} &fshod."
    rank_effect: "&d&lRANKS &fEffect haie rank {state} &fshod!"

    wild: "&#ff6428&lWILD &fShoma be yek jaye random teleport shodid."
    wild_unavailable: "Locatione bi khatari peida nashod, dobare emtehan konid."

    jump: "&#FAD028&lTELEPORT &fShoma roye on block teleport shodid."
    jump_no_access: "Shoma nemitonid dar claim baghie jump bezanid."
    jump_invalid_target: "Shoma nemitavanid bar rooye an block teleport shavid."

    top: "&#FAD028&lTELEPORT &fShoma roye on block teleport shodid."
    top_no_access: "Shoma nemitonid dar claim baghie top bezanid."
    top_invalid_target: "Shoma nemitavanid bar rooye an block teleport shavid."

    hat_available: "Shoma darhale hazer helmet darid."
    hat_invalid: "Nemitavanid az in item be onvane helmet estefade konid."

    smelt: "{smelt_prefix} Itemi ke dar dast dashtid smelt shod."
    smelt_all: "{smelt_prefix} Tamame item hai ke dar inventory dashtid smelt shodand."

    repair_item_invalid: "Itemi ke dar dast darid nemitavan tamir kard."
    repair: "{repair_prefix} Iteme dasteton tamir shod."
    repair_all: "{repair_prefix} Tamame item hai ke dar inventory bood tamir shod."

    weather_invalid: "Weatheri ke mikhaid vojod nadare."
    weather: "{wheater_prefix} Weather baraye shoma be {weather} taghir yaft."
    time_invalid: "Timei ke mikhaid vojod nadare."
    time: "{time_prefix} Time be {time} taghir yaft."
    near: "{near_prefix} &fPlayer haye nazdik shoma: \n"
    near_none: "Hich playeri dar nazdikie shoma vojod nadare."

    sign_edit_line_invalid: "Adadi ke vared kardi hatman bayad beine 1-4 bashad."
    sign_text_invalid: "Shoma nemitavanid hamchin texti ro roye sign benevisid."
    sign_edit_private: "Shoma nemitonid in sign ro edit konid."
    sign_edit_no_access: "Shoma nemitonid dar claim baghie in command ro ejra konid."
    sign_edit_invalid: "Blocke morede nazar sign nist."
    sign_edit: "{signedit_prefix} &fMatn sign avaz shod."

    spawn:
      set: "{paradise_prefix} &fLocatione jadide spawn be &b{location}&f set shod."
      not_set: "Location spawn taiin nashode ast."

    skull: "{skull_prefix} &fShoma heade {player} &fra daryaft kardid."

    spawner:
      change: "&6&lSPAWNER &fSpawner ba movafaghiat change shod! &6({current}/{limit}) &c-{amount}$"
      no_access: "Shoma nemitonid spawner baghie ro change bedid."
      limit: "Shoma be limite rozane spawner change residid! &4({current}/{limit})"
      invalid: "Be blocki ke negah mikonid spawner nist."
      insufficient_funds: "Shoma pole kafi baraye change nadarid."
      invalid_type: "In mob vojod nadarad lotfan yeki dige entekhab konid."
      same_type: "In spawner dar hale hazer hamin type ast."
      unclaimed: "Lotfan baraye change spawner aval claim konid."

    warp:
      duplicate: "Warpi ke vared kardi az ghabl vojod dashte."
      non_existent: "Warpi peyda nashod."
      create: "&a&lWARPS &fShoma warp be esm {name} sakhtid."
      remove: "&a&lWARPS &fWarp {name} hazf shod."

    economy:
      insufficient_funds: "In player enghadr pool nadarad. Current Balance: {balance}"
      give: "{paradise_prefix} &fYou have added &a+{amount}&f to {player}'s &3{type}&f. Balance: {balance}&f."
      take: "{paradise_prefix} &fYou took &a+{amount}&f from {player}'s &3{type}&f. Balance: {balance}&f."
      set: "{paradise_prefix} &fYou set {player}'s &3{type}&f to &a{amount}&f."
      reset: "{paradise_prefix} &fYou have reset {player}'s &3{type}&f back to &a{balance}&f."

    bank:
      invalid_amount: "Shoma bayad adadi balatar az 0 estefade konid."
      insufficient_funds: "Shoma poole kafi baraye anjame inkar nadarid."
      deposit: "{prefix} &fShoma be bank &c-{amount}&4$&f variz kardid."
      withdraw: "{prefix} &fShoma az bank &a+{amount}&2$&f bardasht kardid."
      balance: "{prefix} &fBank Balance: &2$&a{amount}"
      interest: "{prefix} &fSoode banki shoma &#2ee5b2{amount}$ &fmibashad."
      next_interest: "{prefix} &fSoode banki shoma &#2ee5b2{time} &fdigar variz mishavad."
      player_balance: "{prefix} &f{player} &a{amount} &fdar bank darad."

    pay:
      self: "Shoma nemitoonid be khodeton pay konid."
      insufficient_funds: "Shoma poole kafi baraye anjame inkar nadarid."
      successful_sender: "{economy_prefix} &fShoma &a{amount}&2$&f money be {player} ferestadid."
      successful_receiver: "{economy_prefix} &a{amount}&2$&f money be poole shoma tavasote {player} ezafe shod."

    home:
      reached_limit: "Shoma bishtar az {limit} nemitavanid Home besazid."
      invalid_world: "Shoma nemitavanid dar spawn Home besazid."

      untrusted: "Shoma nemitavanid dar claim baghie sethome bezanid."
      duplicate: "In home az ghabl vojod darad."

      create_usage: "Usage: /sethome <name>"
      create: "{prefix} &fHome be esme {name} sakhte shod."
      delete: "{prefix} &f{name} hazf shod."
      delete_invalid: "&fHome be esme {name} peyda nashod."

      list:
        self: "{prefix} &fHomes: {names}."
        empty_self: "Shoma home nadarid."
        others: "{prefix} &f{player}'s Homes: {names}."
        empty_others: "{prefix} &f{player} doesn't have any homes."

      teleport: "{prefix} &fTeleported to {name}."
      teleport_other: "{prefix} &fTeleported to {player}'s {name}."

      invalid_name: "Shoma hatman bayad az horof monaseb estefade konid va kochik tar az 3 ya bozorgtar az 16 nabashad."
      not_found: "Home peyda nashod."

    balance:
      self: "{economy_prefix} &fBalance: &2$&a{balance}"
      others: "{economy_prefix} &f{player}'s balance: &2$&a{balance}"

      top:
        no_users: "Player peyda nashod."
        empty: ""
        footer: "&c&l * &f/baltop {page} baraye raftan be safheye bad."
        body: " &f{rank}. &7{player} &8- &2$&a{balance}"
        extra: "&fPage: &7{page}&f, Loaded players: &7{users}"

    kit: "{kit_prefix} &fShoma kit {kit_name} daryaft kardid, Shoma mitavanid in kit ra bad az {cooldown} dobare begirid."
    kit_staff: "{paradise_prefix} &fShoma kit {kit_name} daryaft kardid."
    kit_no_permission: "Shoma haghe gereftane in kit ra nadarid."
    kit_invalid: "In kit vojod nadarad."
    kit_cooldown: "{kit_name} ro mitoonin bad az {cooldown} dobare begirid."